% Hua-sheng XIE, IFTS-ZJU, huashengxie@gmail.com, 2011-07-02 16:15
% clear;clc;
run=['K=str2num(get(heditK,''String''));'...
    'Np=str2num(get(heditNp,''String''));'...
    'Nstep=str2num(get(heditNstep,''String''));'...
    'standardmap_fun(K,Np,Nstep,get(hcplotpq0,''value''),'...
    'get(hcpperiod,''value''),get(hpinitial,''value''),hAxes1);'];
hf=figure('unit','normalized','Position',[0.25 0.25 0.5 0.5],...
            'Name','Standard Mapping',... % 'menubar','none',...
            'NumberTitle','off');
hAxes1=axes('unit','normalized','position',[0.07 0.15 0.72 0.75],...
        'Box','on');
% hAxes2=axes('unit','normalized','position',[0.07 0.1 0.72 0.35],...
%         'Box','on');
    
htextK=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.9 0.1 0.05],'max',2,'string','K');    
htextNp=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.8 0.1 0.05],'max',2,'string','N points');    
htextNstep=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.7 0.1 0.05],'max',2,'string','N steps');

heditK=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.87 0.1 0.05],'string','1.0');
heditNp=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.77 0.1 0.05],'string','100');
heditNstep=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.67 0.1 0.05],'string','500');
        
htextplotpq0=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[0.88 0.55 0.1 0.03],'max',2,'string','plot (q0,p0)');
hcplotpq0=uicontrol(hf,'unit','normalized','style','check','position',...
                [0.85 0.55 0.03 0.03],'value',0);
htextpperiod=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[0.87 0.5 0.1 0.03],'max',2,'string','p period');
hcpperiod=uicontrol(hf,'unit','normalized','style','check','position',...
                [0.85 0.5 0.03 0.03],'value',0);
            
hpinitial=uicontrol(hf,'Style','popupmenu',...
         'unit','normalized','Position',[0.85 0.44 0.13 0.05],...
         'String','rand p&q|q0=0|p0=0',...
         'Value',1);
        
        
hbrun=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.3 0.1 0.05],...
                'String','Run',...
                'Callback',run);         
hbclear=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.2 0.1 0.05],...
                'String','Clear',...
                'Callback','cla'); 
            
hbexit=uicontrol(hf,'style','push',...
               'unit','normalized','position',[0.85 0.1 0.1 0.05],...
               'callback','close',...
               'string','Exit');