% Hua-sheng XIE, IFTS-ZJU, huashengxie@gmail.com, 2011-06-26 21:34
% tokamak_drawbline_gui.m, call tokamak_drawbline.m
% draw B field line of tokamak based on q-profile, q=n/m
% clear;clc;
draw=['R=str2num(get(hedit1,''String''));'...
    'r=str2num(get(hedit2,''String''));'...
    'n=str2num(get(hedit3,''String''));'...
    'm=str2num(get(hedit4,''String''));'...  
    'tokamak_drawbline_fun(R,r,n,m);ud=get(hp1,''UserData'');',...
    'view(ud(get(hp1,''Value''),1),ud(get(hp1,''Value''),2));'...
    'zoom on;'];

hf=figure('unit','normalized','Position',[0.3 0.3 0.4 0.4],...
            'Name','Draw B field line of tokamak based on q-profile, q=n/m',... % 'menubar','none',...
            'NumberTitle','off');
ha=axes('unit','normalized','position',[0.07 0.1 0.72 0.8],...
        'Box','on');

htext1=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.9 0.1 0.05],'max',2,'string','R');
htext2=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.8 0.1 0.05],'max',2,'string','a');
htext3=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.7 0.1 0.05],'max',2,'string','n');
htext4=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.6 0.1 0.05],'max',2,'string','m');

hedit1=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.87 0.1 0.05],'string','5.0');
hedit2=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.85 0.77 0.1 0.05],'string','1.0');
hedit3=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.67 0.1 0.05],'string','2');
hedit4=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.85 0.57 0.1 0.05],'string','7');

hb1=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.3 0.1 0.05],...
                'String','Draw',...
                'Callback',draw);
hb2=uicontrol(hf,'style','push',...
               'unit','normalized','position',[0.85 0.2 0.1 0.05],...
               'callback','close',...
               'string','Exit');
% hb3=uicontrol(hf,'style','push',...
%                'unit','normalized','position',[0.85 0.1 0.1 0.05],...
%                'callback','demo',...
%                'string','Back');
           
hp1=uicontrol(hf,'Style','popupmenu',...
         'unit','normalized','Position',[0.85 0.4 0.13 0.05],...
         'String','view 3d|view xy|view xz|view yz',...
         'Value',1,...
         'UserData',[[-45 45];...
                   [0 90];...
                   [0 0];...
                   [90 0]],...
         'CallBack',draw);