% Hua-sheng XIE, IFTS-ZJU, huashengxie@gmail.com, 2011-06-26 21:34
% tokamak_drawbline_gui.m, call tokamak_drawbline.m
% draw B field line of tokamak based on q-profile, q=n/m
% clear;clc;
draw=['x0=str2num(get(hedit1,''String''));'...
    'kappa=str2num(get(hedit2,''String''));'...
    'delta=str2num(get(hedit3,''String''));'...
    'b0=str2num(get(hedit4,''String''));'...  
    'tokamak_shape_fun(x0,kappa,delta,b0);'];

hf=figure('unit','normalized','Position',[0.3 0.3 0.4 0.4],...
            'Name','Draw tokamak cross section shape',... % 'menubar','none',...
            'NumberTitle','off');
ha=axes('unit','normalized','position',[0.1 0.1 0.7 0.8],...
        'Box','on');

htext1=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.9 0.1 0.05],'max',2,'string','X0');
htext2=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.8 0.1 0.05],'max',2,'string','¦Ê');
htext3=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.7 0.1 0.05],'max',2,'string','¦Ä');
htext4=uicontrol(hf,'unit','normalized','style','text','backgroundcolor',[0.8 0.8 0.8],...
               'position',[ 0.85 0.6 0.1 0.05],'max',2,'string','b');

hedit1=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.87 0.1 0.05],'string','5.0');
hedit2=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.85 0.77 0.1 0.05],'string','1.4');
hedit3=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[ 0.85 0.67 0.1 0.05],'string','0.0');
hedit4=uicontrol(hf,'unit','normalized','style','edit','backgroundcolor',[1 1 1],...
            'position',[0.85 0.57 0.1 0.05],'string','0.8');

hb1=uicontrol(hf,'Style','pushbutton',...
                'unit','normalized','Position',[0.85 0.3 0.1 0.05],...
                'String','Draw',...
                'Callback',draw);
hb2=uicontrol(hf,'style','push',...
               'unit','normalized','position',[0.85 0.2 0.1 0.05],...
               'callback','close',...
               'string','Exit');




