clear;clc;
a=0.35;
[X,Y]=meshgrid(0:0.1:1);
XY=X.^2+Y.^2;
k2=4*a*X./(a^2+XY+2*a*X);
[K,E]=ellipke(k2);
aXY=a^2+XY-2*a*X;
aXY=aXY+eps*(aXY==0);
aE1=(a^2-XY)./aXY.*E;
aE2=(a^2+XY)./aXY.*E;
By=1/pi./sqrt(a^2+XY+2*a*X).*(aE1+K);
Bx=1/pi*Y./(X+eps*(X==0))./sqrt(a^2+XY+2*a*X).*(aE2-K);
vy=0; vx=[0.0001:0.01:0.35];
[Vx, Vy]=meshgrid(vx,vy);
streamline(X,Y,Bx,By,Vx,Vy);
hold on;
streamline(-X,Y,-Bx,By,-Vx,Vy);
streamline(-X,-Y,-Bx,-By,-Vx,-Vy);
streamline(X,-Y,Bx,-By,Vx,-Vy);